name: custom_date_range_picker
description: A Flutter package for both android and iOS which provides a custom date range picker
version: 1.0.10
homepage: https://github.com/El-Mazouzi/custom_date_range_picker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
